### ISSUE TITLE
Use rspec instead minitests in Getting Started

### ISSUE THREAD

**Issue by davydovanton** [hanami/hanami.github.io#365]
@hanami/core WDYT?

**Comment by cllns** [comment]
I'm rewriting the Interactor guide now, and I wrote this down in my notes as something to bring up :)

I think we should do this. When I was first introduced to Hanami and going through the 'Getting Started' guide, I liked that Hanami used `Minitest::Spec`, since I hadn't used it before. It was simple enough to learn and went along with _simplicity_ message. 

Now, especially since Hanami itself uses RSpec, I feel like it could be a distraction. People might wrongly infer that Hanami prefers Minitest over RSpec. And, as we inevitably touch into mocking and stubbing (like for the Interactor guide), we have to do some odd things in `Minitest::Spec` that are quite obvious in Rspec.

Ideally we could do both, but I don't think the overhead for that is worth it at this point :)

**Comment by jodosha** [comment]
👍 for RSpec

**Comment by davydovanton** [comment]
Okay, I'll replace it for 1.1 getting started guide 👍

**Comment by cllns** [comment]
@davydovanton Actually, I can take this one. I have to update the [`hanami/bookshelf`](https://github.com/hanami/bookshelf) app accordingly, and I'm taking the opportunity to rewrite it as well, to improve clarity :)

**Comment by cllns** [comment]
This was done in #429 which was ported over to the `hanami/guides` repo (where guides live now): https://github.com/hanami/guides/pull/3/
