### ISSUE TITLE
Disable HTTP and redirect to HTTPS?

### ISSUE THREAD

**Issue by prio101** [hanami/hanami.github.io#513]
- Hanami Main Site is lacking SSL , maybe its expired now.
- please check.

reference link: http://hanamirb.org/

**Comment by cllns** [comment]
The SSL certificate is valid (right now I see: `Not before: 9/27/2020,`,` Not after: 12/26/2020`) at https://hanamirb.org

I guess we could disable the HTTP site and redirect to HTTPS (my browser with a plugin already does that for me). It seems like a low priority since it's just a marketing/documentation site, but I'm going to rename this issue so others can chime in (and close if they feel necessary).

**Comment by prio101** [comment]
@cllns yep... i guess a redirector entry will be great.

**Comment by jodosha** [comment]
@prio101 @cllns Our website is hosted by GH Pages. I discovered today that they enabled an option for enforcing HTTPS, which it's now on for the website. Thank you all. 👍 

![Screenshot 2020-11-17 at 09 32 26](https://user-images.githubusercontent.com/5089/99365692-ed485980-28b7-11eb-95e0-4e2151043ff8.png)

**Comment by cllns** [comment]
Closing because this was resolved in November. Just verified it's still working too

```shell
% wget hanamirb.org
--2021-05-07 12:15:01--  http://hanamirb.org/
Resolving hanamirb.org (hanamirb.org)... 185.199.109.153, 185.199.111.153, 185.199.110.153, ...
Connecting to hanamirb.org (hanamirb.org)|185.199.109.153|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://hanamirb.org/ [following]
--2021-05-07 12:15:01--  https://hanamirb.org/
Connecting to hanamirb.org (hanamirb.org)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18384 (18K) [text/html]
Saving to: ‘index.html’

index.html          100%[===================>]  17.95K  --.-KB/s    in 0.006s

2021-05-07 12:15:01 (2.84 MB/s) - ‘index.html’ saved [18384/18384]
```
